// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

const { IndexEncoder, c } = require('hyperdb/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

// '@hyperdiscovery/manifest' collection key
const collection0_key = new IndexEncoder([], { prefix: 0 })

function collection0_indexify(record) {
  return []
}

// '@hyperdiscovery/manifest' value encoding
const collection0_enc = getEncoding('@hyperdiscovery/manifest')

// '@hyperdiscovery/manifest' reconstruction function
function collection0_reconstruct(version, keyBuf, valueBuf) {
  setVersion(version)
  const record = c.decode(collection0_enc, valueBuf)
  return record
}
// '@hyperdiscovery/manifest' key reconstruction function
function collection0_reconstruct_key(keyBuf) {
  return {}
}

// '@hyperdiscovery/manifest'
const collection0 = {
  name: '@hyperdiscovery/manifest',
  id: 0,
  encodeKey(record) {
    const key = []
    return collection0_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection0_enc, record)
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: []
}

// '@hyperdiscovery/swarms' collection key
const collection1_key = new IndexEncoder([IndexEncoder.BUFFER], { prefix: 1 })

function collection1_indexify(record) {
  const a = record.publicKey
  return a === undefined ? [] : [a]
}

// '@hyperdiscovery/swarms' value encoding
const collection1_enc = getEncoding('@hyperdiscovery/swarm/hyperdb#1')

// '@hyperdiscovery/swarms' reconstruction function
function collection1_reconstruct(version, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection1_enc, valueBuf)
  record.publicKey = key[0]
  return record
}
// '@hyperdiscovery/swarms' key reconstruction function
function collection1_reconstruct_key(keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    publicKey: key[0]
  }
}

// '@hyperdiscovery/swarms'
const collection1 = {
  name: '@hyperdiscovery/swarms',
  id: 1,
  encodeKey(record) {
    const key = [record.publicKey]
    return collection1_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection1_enc, record)
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: []
}

// '@hyperdiscovery/swarms-by-updated' collection key
const index2_key = new IndexEncoder([IndexEncoder.UINT], { prefix: 2 })

function index2_indexify(record) {
  const a = record.updated
  return a === undefined ? [] : [a]
}

// '@hyperdiscovery/swarms-by-updated'
const index2 = {
  name: '@hyperdiscovery/swarms-by-updated',
  id: 2,
  encodeKey(record) {
    return index2_key.encode(index2_indexify(record))
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return index2_key.encodeRange({
      gt: gt ? index2_indexify(gt) : null,
      lt: lt ? index2_indexify(lt) : null,
      gte: gte ? index2_indexify(gte) : null,
      lte: lte ? index2_indexify(lte) : null
    })
  },
  encodeValue: (doc) => index2.collection.encodeKey(doc),
  encodeIndexKeys(record, context) {
    return [index2_key.encode([record.updated])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index2)

const collections = [collection0, collection1]

const indexes = [index2]

module.exports = { version, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection(name) {
  switch (name) {
    case '@hyperdiscovery/manifest':
      return collection0
    case '@hyperdiscovery/swarms':
      return collection1
    default:
      return null
  }
}

function resolveIndex(name) {
  switch (name) {
    case '@hyperdiscovery/swarms-by-updated':
      return index2
    default:
      return null
  }
}
