// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

const { IndexEncoder, c, b4a } = require('hyperdb/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const versions = { schema: version, db: 1 }

// '@hypertracker/manifest' collection key
const collection0_key = new IndexEncoder([], { prefix: 0 })

function collection0_indexify(record) {
  return []
}

// '@hypertracker/manifest' value encoding
const collection0_enc = getEncoding('@hypertracker/manifest')

// '@hypertracker/manifest' reconstruction function
function collection0_reconstruct(schemaVersion, keyBuf, valueBuf) {
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  return record
}
// '@hypertracker/manifest' key reconstruction function
function collection0_reconstruct_key(keyBuf) {
  return {}
}

// '@hypertracker/manifest'
const collection0 = {
  name: '@hypertracker/manifest',
  id: 0,
  version: 1,
  encodeKey(record) {
    const key = []
    return collection0_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue(schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@hypertracker/swarms' collection key
const collection1_key = new IndexEncoder([IndexEncoder.BUFFER], { prefix: 1 })

function collection1_indexify(record) {
  const a = record.publicKey
  return a === undefined ? [] : [a]
}

// '@hypertracker/swarms' value encoding
const collection1_enc = getEncoding('@hypertracker/swarm/hyperdb#1')

// '@hypertracker/swarms' reconstruction function
function collection1_reconstruct(schemaVersion, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection1.decodedVersion = c.uint.decode(state)
  const record = collection1_enc.decode(state)
  record.publicKey = key[0]
  return record
}
// '@hypertracker/swarms' key reconstruction function
function collection1_reconstruct_key(keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    publicKey: key[0]
  }
}

// '@hypertracker/swarms'
const collection1 = {
  name: '@hypertracker/swarms',
  id: 1,
  version: 1,
  encodeKey(record) {
    const key = [record.publicKey]
    return collection1_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue(schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection1_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection1_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@hypertracker/swarms-by-updated' collection key
const index2_key = new IndexEncoder([IndexEncoder.UINT], { prefix: 2 })

function index2_indexify(record) {
  const a = record.updated
  return a === undefined ? [] : [a]
}

// '@hypertracker/swarms-by-updated'
const index2 = {
  name: '@hypertracker/swarms-by-updated',
  version: 1,
  id: 2,
  encodeKey(record) {
    return index2_key.encode(index2_indexify(record))
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return index2_key.encodeRange({
      gt: gt ? index2_indexify(gt) : null,
      lt: lt ? index2_indexify(lt) : null,
      gte: gte ? index2_indexify(gte) : null,
      lte: lte ? index2_indexify(lte) : null
    })
  },
  encodeValue: (record) => index2.collection.encodeKey(record),
  encodeIndexKeys(record, context) {
    return [index2_key.encode([record.updated])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index2)

const collections = [collection0, collection1]

const indexes = [index2]

module.exports = { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection(name) {
  switch (name) {
    case '@hypertracker/manifest':
      return collection0
    case '@hypertracker/swarms':
      return collection1
    default:
      return null
  }
}

function resolveIndex(name) {
  switch (name) {
    case '@hypertracker/swarms-by-updated':
      return index2
    default:
      return null
  }
}
