// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @hypertracker/manifest
const encoding0 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.fixed32.preencode(state, m.seed)
  },
  encode(state, m) {
    c.uint.encode(state, m.version)
    c.fixed32.encode(state, m.seed)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.fixed32.decode(state)

    return {
      version: r0,
      seed: r1
    }
  }
}

// @hypertracker/swarm
const encoding1 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.publicKey)
    state.end++ // max flag is 4 so always one byte

    if (m.bumped) c.uint.preencode(state, m.bumped)
    if (m.updated) c.uint.preencode(state, m.updated)
    if (m.signature) c.fixed64.preencode(state, m.signature)
  },
  encode(state, m) {
    const flags = (m.bumped ? 1 : 0) | (m.updated ? 2 : 0) | (m.signature ? 4 : 0)

    c.fixed32.encode(state, m.publicKey)
    c.uint.encode(state, flags)

    if (m.bumped) c.uint.encode(state, m.bumped)
    if (m.updated) c.uint.encode(state, m.updated)
    if (m.signature) c.fixed64.encode(state, m.signature)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const flags = c.uint.decode(state)

    return {
      publicKey: r0,
      bumped: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      updated: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      signature: (flags & 4) !== 0 ? c.fixed64.decode(state) : null
    }
  }
}

// @hypertracker/announce
const encoding2 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.bump) c.uint.preencode(state, m.bump)
  },
  encode(state, m) {
    const flags = m.bump ? 1 : 0

    c.uint.encode(state, flags)

    if (m.bump) c.uint.encode(state, m.bump)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      bump: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @hypertracker/announce-to-swarm.announce
const encoding3_1 = c.frame(encoding2)

// @hypertracker/announce-to-swarm
const encoding3 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.publicKey)
    encoding3_1.preencode(state, m.announce)
    c.fixed64.preencode(state, m.signature)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.publicKey)
    encoding3_1.encode(state, m.announce)
    c.fixed64.encode(state, m.signature)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = encoding3_1.decode(state)
    const r2 = c.fixed64.decode(state)

    return {
      publicKey: r0,
      announce: r1,
      signature: r2
    }
  }
}

// @hypertracker/subscribe-to-swarm
const encoding4 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.publicKey)
    c.uint.preencode(state, m.since)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.publicKey)
    c.uint.encode(state, m.since)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)

    return {
      publicKey: r0,
      since: r1
    }
  }
}

// @hypertracker/unsubscribe-to-swarm
const encoding5 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.publicKey)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.publicKey)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)

    return {
      publicKey: r0
    }
  }
}

// @hypertracker/bump-from-swarm
const encoding6 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.publicKey)
    c.uint.preencode(state, m.bumped)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.publicKey)
    c.uint.encode(state, m.bumped)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)

    return {
      publicKey: r0,
      bumped: r1
    }
  }
}

// @hypertracker/swarm/hyperdb#1
const encoding7 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.bumped) c.uint.preencode(state, m.bumped)
    if (m.updated) c.uint.preencode(state, m.updated)
    if (m.signature) c.fixed64.preencode(state, m.signature)
  },
  encode(state, m) {
    const flags = (m.bumped ? 1 : 0) | (m.updated ? 2 : 0) | (m.signature ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.bumped) c.uint.encode(state, m.bumped)
    if (m.updated) c.uint.encode(state, m.updated)
    if (m.signature) c.fixed64.encode(state, m.signature)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      publicKey: null,
      bumped: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      updated: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      signature: (flags & 4) !== 0 ? c.fixed64.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@hypertracker/manifest':
      return encoding0
    case '@hypertracker/swarm':
      return encoding1
    case '@hypertracker/announce':
      return encoding2
    case '@hypertracker/announce-to-swarm':
      return encoding3
    case '@hypertracker/subscribe-to-swarm':
      return encoding4
    case '@hypertracker/unsubscribe-to-swarm':
      return encoding5
    case '@hypertracker/bump-from-swarm':
      return encoding6
    case '@hypertracker/swarm/hyperdb#1':
      return encoding7
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
