name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: npm t
      - run: npm run test:bare
      - run: npm run lint
